---
name: ma-patrick-ritzenfeld
extra-source-files: [ ]
dependencies:
  - base
  - blaze-html
  - blaze-markup
  - extra
  - fast-logger
  - parsec
  - shakespeare
  - text
  - transformers
  - yesod
  - yesod-core
default-extensions:
  - TupleSections
  - DuplicateRecordFields
  - OverloadedLabels
  - MultiParamTypeClasses
  - FlexibleInstances
  - TypeApplications
  - ScopedTypeVariables
  - NamedFieldPuns
  - FlexibleContexts
library:
  source-dirs: src
  exposed-modules:
    - FlexTask.FormUtil
    - FlexTask.Generic.Form
    - FlexTask.Generic.Parse
    - FlexTask.YesodConfig
  ghc-options:
    - -Wall
    - -Widentities
    - -Werror
    - -Wno-x-partial
tests:
  ma-patrick-ritzenfeld-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Widentities
      - -Werror
    dependencies:
      - ma-patrick-ritzenfeld
      - hspec
