---
resolver: nightly-2024-03-20
packages:
  - flex-tasks
  - flex-tasks-processing
extra-deps:
  - git: https://github.com/fmidue/output-blocks.git
    commit: c8b60a9045a6cc5f1229974701c0d31445543786
    subdirs:
      - output-blocks
