---
resolver: nightly-2025-07-23
packages:
  - flex-tasks
  - flex-tasks-processing
extra-deps:
  - git: https://github.com/fmidue/output-blocks.git
    commit: 77d9867b1d872795064086836e1b0cf24bcfd296
    subdirs:
      - output-blocks
