---
resolver: nightly-2025-10-07
packages:
  - flex-tasks
  - flex-tasks-processing
extra-deps:
  - git: https://github.com/fmidue/output-blocks.git
    commit: d67590cb2e1a72ed72437a8cfe2972b680405569
    subdirs:
      - output-blocks
  # for output-blocks
  - git: https://git.uni-due.de/fmi/autotool-dev.git
    commit: 56e75cd74d44f81ae52baa3b886025bd4d158bbb
    subdirs:
      - base
      - data
      - reader
      - todoc
      - transport
      - util
