---
resolver: nightly-2024-03-20
packages:
  - flex-tasks
  - flex-tasks-processing
extra-deps:
  - git: https://github.com/fmidue/output-blocks.git
    commit: 15eec5a92d4d372233dc1180f0d68beb9d42fe9d
    subdirs:
      - output-blocks
