---
name: flex-tasks
version: 0.1
extra-source-files:
  - tasks/defaultConfig.flex
dependencies:
  - base
  - blaze-html
  - containers
  - directory
  - extra
  - fast-logger
  - filepath
  - ghc
  - hint
  - file-embed
  - flex-tasks-processing
  - mtl
  - output-blocks
  - parsec
  - parsec-numbers
  - QuickCheck
  - raw-strings-qq
  - SHA
  - shakespeare
  - text
  - transformers
  - utf8-string
  - yesod
  - yesod-core
default-extensions:
  - TupleSections
  - OverloadedLabels
  - MultiParamTypeClasses
  - FlexibleInstances
  - TypeApplications
  - ScopedTypeVariables
  - NamedFieldPuns
  - FlexibleContexts
library:
  source-dirs: src
  exposed-modules:
    - FlexTask.DefaultConfig
    - FlexTask.FormUtil
    - FlexTask.Generic.Form
    - FlexTask.Generic.Parse
    - FlexTask.InterpreterHelper
    - FlexTask.Interpreter
    - FlexTask.Types
    - FlexTask.YesodConfig
  ghc-options:
    - -Wall
    - -Widentities
    - -Werror
tests:
  flex-tasks-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Widentities
      - -Werror
    dependencies:
      - autotool-capabilities
      - autotool-capabilities-io-instances
      - flex-tasks
      - flex-tasks-processing
      - hspec
      - hspec-parsec
      - quickcheck-instances
      - string-interpolate
      - syb
  flex-tasks-doctest:
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    main: DocTest.hs
    source-dirs:
      - doctest
    dependencies:
      - doctest
      - doctest-discover
      - flex-tasks
      - flex-tasks-processing
