---
default: true
extends: null

# Unordered list indentation
MD007:
  # Spaces for indent
  indent: 4
  # Whether to indent the first level of the list
  start_indented: false
  # Spaces for first level indent (when start_indented is set)
  start_indent: 2

# Multiple consecutive blank lines
MD012:
  # Consecutive blank lines
  maximum: 2

# Line length
MD013:
  # Number of characters
  line_length: 150
  # Number of characters for headings
  heading_line_length: 150
  # Number of characters for code blocks
  code_block_line_length: 150
  # Include code blocks
  code_blocks: true
  # Include tables
  tables: true
  # Include headings
  headings: true
  # Strict length checking
  strict: false
  # Stern length checking
  stern: false

# Lists should be surrounded by blank lines
MD032: false

