---
name: flex-task-processing
extra-source-files: [ ]
dependencies:
  - base
  - text
default-extensions:
  - TupleSections
  - DuplicateRecordFields
  - OverloadedLabels
  - MultiParamTypeClasses
  - FlexibleInstances
  - TypeApplications
  - ScopedTypeVariables
  - NamedFieldPuns
  - FlexibleContexts
library:
  source-dirs: src
  exposed-modules:
    - FlexTask.Processing.Text
  ghc-options:
    - -Wall
    - -Widentities
    - -Werror
    - -Wno-x-partial
tests:
  flex-task-test:
    main: Spec.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Widentities
      - -Werror
    dependencies:
      - flex-task-processing
      - hspec
