---
resolver: nightly-2024-03-20
packages:
  - .
extra-deps:
  - git: https://github.com/fmidue/flex-tasks.git
    commit: 7d2e9afad03b16168d0c32c42008ca42da0487c8
    subdirs:
      - flex-tasks
      - flex-tasks-processing
  - git: https://github.com/fmidue/output-blocks.git
    commit: f14dca13e3fa06858ee6299333764b9b89d820c9
    subdirs:
      - output-blocks
  - git: https://github.com/fmidue/logic-tasks.git
    commit: 8093fa58141f4125fed9004a60c4363babb0470f
  - git: https://github.com/fmidue/term-tasks
    commit: a8c25271c2fa07930dd21d221646d63181e870ce
  - latex-svg-image-0.2@sha256:b282a74a96724037ec3d24b664118e51170c8152aff12f363ddb715a38ef053a,1830

allow-newer: true
allow-newer-deps:
  - latex-svg-image
