---
resolver: nightly-2024-03-20
packages:
  - .
extra-deps:
  - git: https://github.com/fmidue/flex-tasks.git
    commit: 01db994d2125647af01178b3b2ccf8c8181c07b3
    subdirs:
      - flex-tasks
      - flex-tasks-processing
  - git: https://github.com/fmidue/output-blocks.git
    commit: 292954d4803d80e0bed91cb11294a886361ac2a5
    subdirs:
      - output-blocks
  - git: https://github.com/fmidue/logic-tasks.git
    commit: d88f11aec2821d04287a72f1d1373b3866cce42e
  - git: https://github.com/fmidue/term-tasks
    commit: 1786d63d34d0f4e130b34b32b1acf0099b5c41e0
  - latex-svg-image-0.2@sha256:b282a74a96724037ec3d24b664118e51170c8152aff12f363ddb715a38ef053a,1830

allow-newer: true
allow-newer-deps:
  - latex-svg-image
