---
resolver: nightly-2024-03-20
packages:
  - .
extra-deps:
  - git: https://github.com/fmidue/flex-tasks.git
    commit: 438beb3c42a8a6d66a1920ad725502b0c20bae80
    subdirs:
      - flex-tasks
      - flex-tasks-processing
  - git: https://github.com/fmidue/output-blocks.git
    commit: dbc0713b6b8da7d1305bbfbd4d6856a78676e1e1
    subdirs:
      - output-blocks
  - git: https://github.com/fmidue/logic-tasks.git
    commit: 2a06b296cabf7faf79a86a568f326fb52a2492e0
  - latex-svg-image-0.2@sha256:b282a74a96724037ec3d24b664118e51170c8152aff12f363ddb715a38ef053a,1830

allow-newer: true
allow-newer-deps:
  - latex-svg-image
