---
name: Build PKGDB

on:
  push:
    branches: [config-test-workflow]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  build_db:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: pull repo
        run: |
          set -ex
          sudo apt-get update
          sudo apt-get -y install zsh
          git clone https://github.com/fmidue/haskell-template-setup.git
          cd haskell-template-setup
          echo $PWD
          ./create.sh
          set +ex
