---
name: Test Flex Tasks


on:
  push:
    branches: ["comp-action"]
#  repository_dispatch:
#    types: [CI-Completed]

permissions:
  contents: write
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: fmidue/flex-tasks/.github/actions/test-flex@comp-action
        with:
          tasks: flex-tasks/tasks
          config: pkgdb-config
          settings-gens: flex-tasks/tasks/settings-gens
          package-locations: '*'
          subdirs: '[flex-tasks, flex-tasks-processing]'
#          commit: ${{ github.event.client_payload.sha }}
          latex-setup: true
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
