---
name: Haskell Linter

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Set up HLint'
        uses: haskell-actions/hlint-setup@v2
        with:
          version: '3.8'

      - name: 'Run HLint'
        uses: haskell-actions/hlint-run@v2
        with:
          path: '["flex-task/src/", "flex-task-processing/src", "flex-task/test/", "flex-task-processing/test"]'
          fail-on: suggestion
