---
name: Stack Setup Consistency Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  consistency:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: stack.yaml has no additions to stack-test.yaml
        run: "! comm -23 stack.yaml stack-test.yaml --nocheck-order | grep ."
